# Generated by Django 3.1.5 on 2022-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholdername', models.CharField(max_length=200)),
                ('cardnumber', models.CharField(max_length=200)),
                ('cardtype', models.CharField(max_length=200)),
                ('cardexpiry', models.DateTimeField()),
                ('csv', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
