# Generated by Django 3.1.5 on 2022-09-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cardexpiry',
            field=models.DateField(),
        ),
    ]
